name: 'Terraform AWS Distributed Deploy'

on:
  push:
    branches:
      - main # Ejecutar cuando subas código a la rama principal

jobs:
  terraform:
    name: 'Aplicar Infraestructura'
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configurar Credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Estas variables deben ser configuradas como GitHub Secrets
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}  # <<-- ¡NUEVA LÍNEA CLAVE!
          aws-region: us-east-1 # Debe coincidir con tu variable.tf

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform destroy -auto-approve
